package com.app.enums;

public enum Genre {
	SCIENCE_FICTION, SATIRE, DRAMA, ACTION, ADVENTURE, ROMANCE, MYSTERY, HORROR, SELF_HELP, HEALTH, GUIDE, TRAVEL, CHILDRENS, RELIGION, 
	SPIRITUALITY, SCIENCE, HISTORY, MATH, ANTHOLOGY, POETRY, ENCYCLOPEDIAS, DICTIONARIES, COMICS, ART, COOKBOOKS, DIARIES, JOURNALS, PRAYER_BOOKS, 
	SERIES, TRILOGY, BIOGRAPHIES, AUTOBIOGRAPHIES, FANTASY
}
